<?php

/**
 * Implements hook_menu().
 */
function druphone_menu() {
	$items =  array();
	
  $items['admin/settings/druphone'] = array(
		'title'=>'Druphone Settings',
		'description'=>'Edit settings',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('admin_settings_druphone'),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'access arguments' => array('Admin dphone options'),
  );
  
  $items['druphone/regions'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('Admin dphone options'),
    'page callback' => 'druphone_regions',
  );

  return $items;
}

function admin_settings_druphone(){
		
		$themes = list_themes();
		$theme_list = array();
		
		foreach ($themes as $i => $k)
			if ($k -> status)
				$theme_list[$k -> name] = $k -> info['name'];
		
		$form = array();

		$form['theme']=array(
				'#type'=>'select',
				'#title'=>t('Select theme'),
				'#description' => t('Choose an option.'),
				'#required'=>true,
				'#default_value'=>'----',
				'#options' => $theme_list,
				'#validate' => array('admin_settings_druphone_validate')
		);
		
		$form['submit']=array(
				'#type'=>'submit',
				'#value'=>'Save',
				'#weight'=>2);

		return $form;
	}

function admin_settings_druphone_validate($node, &$form_state){
	$themes = $form_state['values']['theme'];
	drupal_set_message("You submitted a valid color: ".$form_state['values']['theme']);
}

function admin_settings_druphone_submit($node, &$form_state){
	
	drupal_set_message("Sumbit");
	
}

function druphone_regions(){
	
	
	
	
}
