<?php

/**
 * Implements hook_menu().
 */
function druphone_menu() {
	$items =  array();
	
  $items['admin/settings/druphone'] = array(
		'title'=>'Druphone Settings',
		'description'=>'Edit settings',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('admin_settings_druphone'),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'access arguments' => array('Admin dphone options'),
  );
  
  $items['druphone/regions/list'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'druphone_regions_list',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  
  $items['druphone/regions'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'druphone_regions',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  
  $items['druphone/script.js'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'druphone_script',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  

  return $items;
}

function admin_settings_druphone(){

		$themes = list_themes();
		$theme_list = array();
		
		foreach ($themes as $i => $k)
			if ($k -> status)
				$theme_list[$k -> name] = $k -> info['name'];
		
		$form = array();

		$form['theme']=array(
				'#type'=>'select',
				'#title'=>t('Select theme'),
				'#description' => t('Choose an option.'),
				'#required'=>true,
				'#default_value'=>'----',
				'#options' => $theme_list,
				'#validate' => array('admin_settings_druphone_validate')
		);
		
		$form['submit']=array(
				'#type'=>'submit',
				'#value'=>'Save',
				'#weight'=>2);

		return $form;
	}

function admin_settings_druphone_validate($node, &$form_state){
	$themes = $form_state['values']['theme'];
	drupal_set_message("You submitted a ".$form_state['values']['theme']);
}

function admin_settings_druphone_submit($node, &$form_state){
	
	drupal_set_message("Sumbit");
	
}

function druphone_regions_list(){
	
	$list = array();
	
	foreach (system_region_list("garland") as $var => $key)
		$list[$var] = $key;
	
	echo json_encode(array('status' => 0, 'data' => $list ));
	
}

function druphone_regions(){
	
	global $theme_key;
	$tmp_theme = $theme_key;
	$tmp_q = $_GET['q'];
	$region = mysql_escape_string ($_POST ['r']);
	$regions = array();
	
	$theme_key = "garland";
	
	$_GET['q'] = mysql_escape_string ($_POST['url']);
	
	$regions[$region] = array("blocks" => json_encode(theme_blocks($region)));

	echo json_encode(array('status' => 0, 'data' => $regions ));
	
	//regresamos las variables a las anteriores
	$theme_key = $tmp_theme;
	$_GET['q'] = $tmp_q;
}


function druphone_script(){
	global $base_url;
	$jsbu = json_encode($base_url."/");
	echo '
		var Drupal = Drupal || { "settings": {}, "behaviors": {}, "themes": {}, "locale": {} };
		jQuery.extend(Drupal.settings, {"basePath":'.$jsbu.'});
		
		function load_blocks(regions){
			
			jQuery.each(regions, function(i,v){
				jQuery.ajax({
					type:"POST",
					dataType:"json",
					data: "r="+i+"&url="+document.location.pathname,
					url:"'.$base_url.'/druphone/regions",
					success: function( data ) {
						console.log("ok");
						$.each(data.data,function(i,v){
							console.log($.parseJSON(v.blocks));
							$("#"+i).append($.parseJSON(v.blocks));
						});
					},
				});
				
			});
		}';
	
	
}
